### PR TITLE
Enable scrolling with smooth scroll

### PR DESCRIPTION
**Pull request by christopher-l**
Still doesn't scroll smoothly, but enables scrolling when only smooth scroll events are emitted.

Not too sure what I'm doing here, so please tell if I used things in ways that weren't intended.

### CODE REVIEW

**Comment by daa84** [comment]
Hello!
Sorry for long response. As i understand this is pixel level scrolling. It is possible to emulate it by storing previous and next state of ui_model while process on_scroll event, but it looks like complex task.

**Comment by christopher-l** [comment]
Hi,
Yes, actual pixel scrolling would be quite hard I guess. However, the reason for my pull request was that even normal scrolling didn't work on my laptop. So I tried to use the smooth scroll events to get normal scrolling, where mouse wheel events aren't available.
Maybe, there is another way to get the system to pass normal scroll events to the application, but by default, it doesn't seem to always do that.

**Comment by daa84** [comment]
Ok, then if it work for you i can merge it.

**Comment by daa84** [comment]
UiState is ok 👍 
Thanks

**Pull request merged**
